[Appearance]
style=kvantum
icon_theme=Papirus-Dark
standard_dialogs=gtk3
custom_palette=false

[Fonts]
fixed="JetBrainsMono Nerd Font,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
general="Noto Sans,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"

[Interface]
cursor_flash_time=1000
buttonbox_layout=0
keyboard_scheme=2
menus_have_icons=true
show_shortcuts_in_context_menus=true
toolbutton_style=4
underline_shortcut=1
wheel_scroll_lines=3
