# fuzzel — application launcher (Catppuccin Mocha)
[main]
font=JetBrainsMono Nerd Font:size=12
dpi-aware=auto
prompt="   "
icon-theme=Papirus-Dark
icons-enabled=yes
fields=name,generic,comment,categories,keywords
terminal=kitty -e
layer=overlay
width=42
lines=12
horizontal-pad=22
vertical-pad=18
inner-pad=10
line-height=24
tabs=4

[colors]
background=1e1e2ef2
text=cdd6f4ff
prompt=cba6f7ff
placeholder=6c7086ff
input=cdd6f4ff
match=cba6f7ff
selection=313244ff
selection-text=cdd6f4ff
selection-match=f5c2e7ff
counter=a6adc8ff
border=cba6f7ff

[border]
width=2
radius=16

[dmenu]
exit-immediately-if-empty=yes

[key-bindings]
cancel=Escape Control+c
execute=Return KP_Enter
